language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
before_install: npm prune
before_cache: npm prune
install: npm install
script: npm test
deploy:
  provider: npm
  email: ops@craft.ai
  api_key:
    secure: eNf/9wOC/uoHKKZGhUG1CGryKHBxuUIUkZhis/TVAGvh65D3LRfWU9kbGTbWmrFV7dQXgMRtZ0OZhevQ5c27gpVZKvIaNZynV53PpBtUwbtOE2vjbdie58PCNo7GKIJsAVfeiQta3pUUq6r9ZyN0573ROch+0pD2bNDLh+YT+JC54lnvGvceOZwajCsITecUgl7aev//6gnWr0cW3TDhNFyhAhpoy0r92g25i4M1IQ8D2nLZ46Wpi0ISL7xlT2DDp45w2ltu1bpJctNhymt1KTduTUbUHymVNceaHzq7llMA4DNhqtXD928JRa/TG2tnor9X7sGd4PUtheEsCJTX7OVrDMQnRnZTMRBXg3VBM/zLoNd6VLh38kddBQfh4cnlqYRyzcPdT5tbBYwmv34BdpdAXoApd0n5hPWkTSBFhFqGcP+h8sU2xv1U96o6X0atCzZdo/2RvUfbqEOdqWRHSOc/suhEyGordJbH3TGE7W0OaWsuUzjm0b+HNcpWKFp2vdhjAgwLxZQ1WvMyXmSOqeQ1GCMbYMjcTiP/U2tpq4+SnNVzeAzZaFJ1TiSS0x18F/hl9FukBOdv1jxXH1AulCxi54EcIZjnMVni7J4oIRz+iMk1qCIS/UbZsEmGIzBWlYGqwKeZTO5eF48M6LBR/+aimhREKvaoyek/dJjdGQE=
  on:
    tags: true
    repo: craft-ai/craft-ai-client-js
    node: '0.12'
  skip_cleanup: true
env:
  global:
    - CRAFT_OWNER=stanley_kubick
    - secure: wbMfuXKdEehLRADjh47kq/vuUAdsdANa1xnM+bWh5a9R22snBEgKQzz3WhGsL2Ag0IjpYE1amhVA4Z14lAMSJ1M99cxlEgLpJkMGy+32+A9V6j7k0Vm0N37/GSUxN7LWoZNXSjhs8jZ6UO1vqI642ByeLlUfzdi09MqVPZgpicR9BqG1W2yR29hHTWSTjjpU3XPB/16AVZAIuPbb2B7MILQwlnhO/gnaT6yTFxwSgYV/e33vH+Tulsubv9Bfqbn0YVsVoqUUopOAMYLeG2LkXK0gFr1TC3Rlw8yHWAicniwMNEkwlqzifJND8HQZ/IJE80Qo3deluxOoE0l6iVQ0BV3QH8Pf93FcbiUaUtdzsSQH6vE6046+I/K7qyeihO/J71SUD/bjPiK1YGjVxV7uzvxk9mYQpBAVyWzpnguHGc6Swn/bmGlQs69D2OjavSZzvG7nTIz3240oMCZ+0BR/tNzZQggEB/+tgAYnd+0Gvz/3f8QntwZjWcb+23aOr7EVBWiNr79RRSFRTksfhzKAHWIu5I9P3GFokZdmOzAlnEYYruFWLqz4CIE2meT9V/UwWQU4gI3SUZpVVttQ8Ji1zVDBl//8BGyFrF/6/yGzsocivWBr+yDoZoDbkGlWaBbwg432CdZPfYn2HjNLIdr/akx4/0eDS8SH+O5IKFdW3Bg=
