language: node_js
node_js:
- '4'
- '0.12'
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
before_cache: npm prune
install: npm install
script: npm test
deploy:
- provider: npm
  email: ops@craft.ai
  api_key:
    secure: eNf/9wOC/uoHKKZGhUG1CGryKHBxuUIUkZhis/TVAGvh65D3LRfWU9kbGTbWmrFV7dQXgMRtZ0OZhevQ5c27gpVZKvIaNZynV53PpBtUwbtOE2vjbdie58PCNo7GKIJsAVfeiQta3pUUq6r9ZyN0573ROch+0pD2bNDLh+YT+JC54lnvGvceOZwajCsITecUgl7aev//6gnWr0cW3TDhNFyhAhpoy0r92g25i4M1IQ8D2nLZ46Wpi0ISL7xlT2DDp45w2ltu1bpJctNhymt1KTduTUbUHymVNceaHzq7llMA4DNhqtXD928JRa/TG2tnor9X7sGd4PUtheEsCJTX7OVrDMQnRnZTMRBXg3VBM/zLoNd6VLh38kddBQfh4cnlqYRyzcPdT5tbBYwmv34BdpdAXoApd0n5hPWkTSBFhFqGcP+h8sU2xv1U96o6X0atCzZdo/2RvUfbqEOdqWRHSOc/suhEyGordJbH3TGE7W0OaWsuUzjm0b+HNcpWKFp2vdhjAgwLxZQ1WvMyXmSOqeQ1GCMbYMjcTiP/U2tpq4+SnNVzeAzZaFJ1TiSS0x18F/hl9FukBOdv1jxXH1AulCxi54EcIZjnMVni7J4oIRz+iMk1qCIS/UbZsEmGIzBWlYGqwKeZTO5eF48M6LBR/+aimhREKvaoyek/dJjdGQE=
  on:
    tags: true
    repo: craft-ai/craft-ai-client-js
    node: '0.12'
  skip_cleanup: true
env:
  global:
  - secure: q2WBbCeYTCCq1R2dFCGLnPGlKlz1IYQYlszhb4ahDWKrqynYXl94TNTOAWfxUoq3qAMICJIgk7lhV3xquYpfshevBMDzRL+EkcquVTfPY4s5FpvPBGd7MqWza4vD9suNg48yUtiJ0ilhR+/PwRVlK79sA0Vti4AzdX1/lzO+xVRzm0tWdLBziwIeMcF98hH0jN/Ssb27FqUo5BgRdJxsGpjCP50UNseE1P5x3ezuNabq088AVseJLIJVMywBwhvjCiXxQu9rjn/lO2TjMM4xf25TEmac4Y4V6u/MEyM2s6hj0L+cz9ZFi01QGsyO9Aj466BvCfcgLaWNubuBuVfz6AuCq/EKASEE8h75yGcU3WVI78KaAELt9jYytHbvkeRaKgKhXMnuj6ZFAy0tMRfKeAOXnIhDnTZ/6U1vEpSjbEGY6/SfLYQTK2VfWl9gzX2slwqj+PLnpPbUHkfVPZEUIyeZ6q3wCCYwrzHE2VYigPyTNLDuxjETXA6SwdPreTK/fUmQl0gw7HwP7NpJPAiTXD/qaK45Srkq9ojHu9QrmUvCisyjw5cfEWefEC9ltgSufLxMkQDVLBxXKnXjIFxzJ6jBLemd+bxI6kMJvUqzNjoWgBsLH3HVYjJVe/0RMDjdwrfYTHnw09bEQymkgBiAtuo1BDpq67OZwzohxEQcCtA=
  - secure: PNNonzbOV4JDgukAopL2Cb3+peFBEh62D/OsYji8JzSICwgbsTohr2DIiU2NRve1tl9In1GqDiF2g7jDHLpm84H8SGKIkpvXNOIAh0/LjixDLus8JrhgcVFFbJeCLojrldchtYEee3S3vpRIMoAw64+PyHh5q8CcatwO5ShFYHsKb4Ga6AC2/ANlrXywzeK2EhX+AXeFKuoF8bzgIQnPf4hPb7pMk62wetfoTj5o/hN3lOco7R1zLAaCTtiu85xa1w/5PJsYJ+NGGO5ptisXu47OT8g1CEX3xQOChFjBYKdRrjryJ4Ic1wWFXpdPK36TR/aKgkq4THa6EngjF9r5soafDtCq1k+wTyvGXLRPHgy74zj77R1JEoxs6Bv1FaMggYqLj7GRj6d5XeMeH4LwZMSygoj+rd+q0Qo5/e9L1yT9GSs3fsMJ7j5TwYYRVBHMm6nLtpZDpX6e7XTe2k1/WvF3TbMCTm5tMmiIkZyXFeu0wHlBEyPsshfWL/pCWZd+m4C5gfZZ6/uPSQDamBsXzV+nsjq1vJPIbMpCCjK+EYuQSOzEzvxkMsjC+4o//PCNvv87hQGj9KgUHgwBnYah2D0vYHzRHWdt6nWpp0rfCaotyUdDkL2Z6XoTDtF1fWeHu9zyurP5v0hxUaoZ9pZtUucld7RPnwOcmi9t7fmwe+E=
  - secure: d6yw5YZZa6VzGBlQj2BF86renwn9vqlaFUvSAMW0KNbUecWkEUqWau2sX49m5cSsJkBBxDzSRo9OtrpGvl7HMAzIrIY2N7xtom/0y+C8i6BxjQ9zIAIQv12/AvJaO/CVYh+Xw2ysPH9ykblUikzldQksJE84ax3eGFCXcWR4po/XWQJWLtge8zuHjngcUQNhPreIB7rsKRott4xzIy7NpJM9B5aWw1v2L2909zlKrIEQpMo2/CV6/uGtRlGYpOYugiBuoqdf0zg+vv/JIyxotKj6V7kAtAvj3gLfy18P437RkyB7GePoiDxNKPiUDdHZHpz2pqgRyeBs2Y7oQdc662/GU1hJFYmYkWqb5iqjj8keZBfApaAvqZtT/5fHTXE2GPn7j1lA7ByB1V96HnyOxrp9oDxbH5FgDP3+l7uvxzLLzoqI1cp5eIWOhiFWKuBfMqYW0Imw3S+SgHPbh1fG/Yld6y1AwOrsDcHhJ7XS+s2dV9NxZDgsclqjKOQLcTr3k+5lReiJqr7SDjJXsl/UjakQzP23CDR58tesCo5gO10XIAzQEfQuLu/OLS3KFezPTdJsIzIP4GOkftYGjzmG4o4SVtHtf0IVlN0ihSK2SQ4zf+r7XeTLUvLUYXuWEiE7R+85yFDCJOAe3J5IxH6TkwjxxgxZKz0cEIXN2EdNCJI=
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email:
  - ops@craft.ai
