language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
before_install: npm prune
before_cache: npm prune
install: npm install
script: npm run test && npm run lint
env:
  global:
  - secure: j2WDJy3n89SMoZ9lH+EANJYexalbyA9ZFWedrGu4bNNa+tSOrnrFgTCrmqIRqh1iEfv+DmQ/uivlMMMhYgwXuAFp242fYIbWyqkOc1fQWhaoLYeo4i11eqJbNLfMx7pA/mK41ED2coGWl7IH83vpxj1zElz8Dd9un1NxCV1zOytwdZcjNw9eV2irKwezKpVm7BRssJ9GcLW7i6q7fpVin8XVPeDcqGZCKRycDdmfpg7MA3pUgSzCtPlgEpDy5xGXNJGHB2iXD3GucoPYr1YurJxFfbmhBmOyPgg0/XgtAQ/IARjshqO/rKtxZ4Ss3xS57mXXzrH0zZcVqFOo4+CycnL37Fbg9dqLL1JT8IerwC6O6pHt9uOasAZ3+iZGi5xVRm+5vSKcJEPrReNDKy/BasM3b/50Vum70DOcAsChL77Xn/IteT7mPC7Sz7vJkREz8QfJwozf6Ghq8OYNVjcrFW6648yI+dSolS/npPmD2NgGMwGY73VRfwoeSuysD0d9GIRArtbhIfw/LDnsJ9MHcerWYdHIGGj77/PKFYmhe0341aTiRx/MT/AKfBCnjRAMcVNHy275xp/L8BbVrMZHT+GJRRzuNpG2yqFr2ownyRWTt02uk1tp8ZUAxWSQa+0lGVwSn7xLRev83HMqqHVTJvP8x5+RDsPGU6eK5LNfgM8=
  - secure: ruqBga06odItWHcQHXYfdOfjDgyFxpgRAr+ZwnzfCecHQ2uRTLEKoLz8DKp+3bDc+ia8jQv0r9vZ45aORFnlpQDou0RgHc1SJW01PObBmLsUYLxycoU0D6wXk0x5IOH15FYFjHEiccyFM+qGiXrhFW27hS+82qlvUvwX7VFiC3UYeIFbZ6kqwFN++4+qkO4f8rcJdnIbrgKZCWHBaCR7E2zQWxXL1XSIBAyr3HXD2xE+g/se+afS8xyqZ8UBTR49Fi/wQDsFpq4GgG+KObWInLY/HA/GuQdD4HGEfrNyITu1Hqk3RV/adtx0skycFzMcI7SONFnNgmjr6FsEKHEbXsHkf/8t5R7ycc8RaOjp+f3oAbodwpecznDvUIbqfy59uUuTeUmRxWPTXouw2T51uswFrkXJBSe59vRzC/z163I5mRtXRr1BhnAPwIGwE9IiMuRGKqLha0DuVMalISN3YUNt2WREWPjt5oR7cQabdLaDVHlTVvRI1/4Sl5Ewk3O9K8Q0OcBrlioGj/K1Yxs/MRXjqeaJzV1zS66ORBchd3tx67n4l2x5T8nh7u6x/cwUy9xU+/HXtfJhmU8a3mCrhk0cD6CM0DuUd5tNPo9/m4TD3k3mx3iLaSOXipNVeCnnOIfI85qyExYmNQv1xFAgkQ+AD2pVcf3N57FyfRCJe2w=
