language: node_js
node_js:
- '4'
- '0.12'
before_install: npm prune
before_cache: npm prune
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install: npm install
script: npm test
deploy:
- provider: npm
  email: ops@craft.ai
  api_key:
    secure: eNf/9wOC/uoHKKZGhUG1CGryKHBxuUIUkZhis/TVAGvh65D3LRfWU9kbGTbWmrFV7dQXgMRtZ0OZhevQ5c27gpVZKvIaNZynV53PpBtUwbtOE2vjbdie58PCNo7GKIJsAVfeiQta3pUUq6r9ZyN0573ROch+0pD2bNDLh+YT+JC54lnvGvceOZwajCsITecUgl7aev//6gnWr0cW3TDhNFyhAhpoy0r92g25i4M1IQ8D2nLZ46Wpi0ISL7xlT2DDp45w2ltu1bpJctNhymt1KTduTUbUHymVNceaHzq7llMA4DNhqtXD928JRa/TG2tnor9X7sGd4PUtheEsCJTX7OVrDMQnRnZTMRBXg3VBM/zLoNd6VLh38kddBQfh4cnlqYRyzcPdT5tbBYwmv34BdpdAXoApd0n5hPWkTSBFhFqGcP+h8sU2xv1U96o6X0atCzZdo/2RvUfbqEOdqWRHSOc/suhEyGordJbH3TGE7W0OaWsuUzjm0b+HNcpWKFp2vdhjAgwLxZQ1WvMyXmSOqeQ1GCMbYMjcTiP/U2tpq4+SnNVzeAzZaFJ1TiSS0x18F/hl9FukBOdv1jxXH1AulCxi54EcIZjnMVni7J4oIRz+iMk1qCIS/UbZsEmGIzBWlYGqwKeZTO5eF48M6LBR/+aimhREKvaoyek/dJjdGQE=
  on:
    tags: true
    repo: craft-ai/craft-ai-client-js
    node: '0.12'
  skip_cleanup: true
env:
  global:
  - secure: CN8LWXkMS733GH9oi401c3L7QB2ZjUDorCWd5R1OZ4oKNEL0Kurvj3NC224Nld1HEEhj8s2eKoRdqL+VSs+DmRrNAbZNQAr+UgfOnOLQoGXSNqqiyMe5HRQMOCxwqdXvS+QIZKG7dbNR/9zNx8NciFUbR3x+8VraDLu5oTs6HO0VCCQijAi40/ka5QTLWCV1OKDTmE0Ubwh2h83rgBV4VeDgohm9MDpe5XDrlPfB7vOfynQ4NOoso+P0uj7BLC32trorlBGuGJ+uUvTJtVwvYj6yuRAXdNlEGWb1k58j60HhbToKXw3/7d66DHg4u8xn2Ztx16yDM3Lw8VQVxGgzUl5LsZ/jVTWWLX2f2wvSQGuQKnnjr4/oXrmlZk5jyUmL4DDmgYC4gQqyn80ZkZKocrGCw2AH2bliAHckNUL38ch3JMJXfcnmjg2/c21xzLwH2f7CRopkTflq0wut6WwlJ7iT/6NACq8c6njCBnxkqIvwouxoUQQuwxoc3yCKcaqix86xjZzq+G7/dcwc8l8DAG+zrr0xjQZHG7lthDTeNvK7CSZx/dsga8NtK46hwOfvPFIOn168hXdy81Wp0px2anRd9SuJGVCNWg8O1PGahsPIA2UFDWWP6yTldXpwuJzlrheb9N7DBh197TYTJt4ozHJJvP3v9/0o6d0BNVfESUo=
  - secure: JWspRMyKMeU9GSro9LHh/B2oY9BeuNvABcBGCyn2ebiS/KfYd5IcLeuLF6zt32XcF7zVoVgWUzMc77IxyIUXwcs3koXuiE3JTsJP5hY11gj7zxb1324wlN4OPy3hxSK9UwzDk3YrW2mn9y4FJmT+7gGJhKQ6PiVrHeuiIlo2C4Thw4jB2S4v35J+Yx/6Z6do2UqiqmEF+ES9819nsHn/PtqSb4szfkHkub3mp+K9ZwOqW2Vti8Xeju3cpG0BCftlJy4/LrcRGqB+lfhzwPxd2NXiVh27x+0IcQqS90fx5WvdwoKPyNfgrcIVYWPBqYHGZD4AEwT32q8ChBfnSmdBiWqmWf25XPe4v6GQf7J9b5inC/iGYJSp1cobVgVKqIl85F3AIcFtmQB7WCg2DAu1GW9tkUFWMFsyAFswDsq52L084UJrgPmjjss7Sl4e/Kp1/itCf/uYsahikIZY4wOLVMtZU5XbxN57ACGh2YIupE4umb5Bi0H3XtDsutMy0ZSuyC2jpJsQxUbvuWDDtroSIV4jqr/ssk6Keds5x9LIkilWiV9UE2gTM6Q0nD41lwSrxXrukhUTuTymdX8YHXAf5AHRhah2R2GqwicYRsIGe/hd2JfUP1rzw2r5FfwKBZCA8nzXvQgZQWcohu5hOruyM8eK8f7fxRwqP0DOuxneeUk=
  - secure: wbMfuXKdEehLRADjh47kq/vuUAdsdANa1xnM+bWh5a9R22snBEgKQzz3WhGsL2Ag0IjpYE1amhVA4Z14lAMSJ1M99cxlEgLpJkMGy+32+A9V6j7k0Vm0N37/GSUxN7LWoZNXSjhs8jZ6UO1vqI642ByeLlUfzdi09MqVPZgpicR9BqG1W2yR29hHTWSTjjpU3XPB/16AVZAIuPbb2B7MILQwlnhO/gnaT6yTFxwSgYV/e33vH+Tulsubv9Bfqbn0YVsVoqUUopOAMYLeG2LkXK0gFr1TC3Rlw8yHWAicniwMNEkwlqzifJND8HQZ/IJE80Qo3deluxOoE0l6iVQ0BV3QH8Pf93FcbiUaUtdzsSQH6vE6046+I/K7qyeihO/J71SUD/bjPiK1YGjVxV7uzvxk9mYQpBAVyWzpnguHGc6Swn/bmGlQs69D2OjavSZzvG7nTIz3240oMCZ+0BR/tNzZQggEB/+tgAYnd+0Gvz/3f8QntwZjWcb+23aOr7EVBWiNr79RRSFRTksfhzKAHWIu5I9P3GFokZdmOzAlnEYYruFWLqz4CIE2meT9V/UwWQU4gI3SUZpVVttQ8Ji1zVDBl//8BGyFrF/6/yGzsocivWBr+yDoZoDbkGlWaBbwg432CdZPfYn2HjNLIdr/akx4/0eDS8SH+O5IKFdW3Bg=
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email:
    - ops@craft.ai
