language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
before_install: npm prune
before_cache: npm prune
install: npm install
script: npm test
deploy:
  provider: npm
  email: ops@craft.ai
  api_key:
    secure: eNf/9wOC/uoHKKZGhUG1CGryKHBxuUIUkZhis/TVAGvh65D3LRfWU9kbGTbWmrFV7dQXgMRtZ0OZhevQ5c27gpVZKvIaNZynV53PpBtUwbtOE2vjbdie58PCNo7GKIJsAVfeiQta3pUUq6r9ZyN0573ROch+0pD2bNDLh+YT+JC54lnvGvceOZwajCsITecUgl7aev//6gnWr0cW3TDhNFyhAhpoy0r92g25i4M1IQ8D2nLZ46Wpi0ISL7xlT2DDp45w2ltu1bpJctNhymt1KTduTUbUHymVNceaHzq7llMA4DNhqtXD928JRa/TG2tnor9X7sGd4PUtheEsCJTX7OVrDMQnRnZTMRBXg3VBM/zLoNd6VLh38kddBQfh4cnlqYRyzcPdT5tbBYwmv34BdpdAXoApd0n5hPWkTSBFhFqGcP+h8sU2xv1U96o6X0atCzZdo/2RvUfbqEOdqWRHSOc/suhEyGordJbH3TGE7W0OaWsuUzjm0b+HNcpWKFp2vdhjAgwLxZQ1WvMyXmSOqeQ1GCMbYMjcTiP/U2tpq4+SnNVzeAzZaFJ1TiSS0x18F/hl9FukBOdv1jxXH1AulCxi54EcIZjnMVni7J4oIRz+iMk1qCIS/UbZsEmGIzBWlYGqwKeZTO5eF48M6LBR/+aimhREKvaoyek/dJjdGQE=
  on:
    tags: true
    repo: craft-ai/craft-ai-client-js
    node: '0.12'
  skip_cleanup: true
env:
  global:
    - CRAFT_OWNER=travis
    - secure: scGZ5mS3gdHtVoLjDCoWcQo3KyU9Vn/o395KyluWqW3oPnnsAxSqIBnj+svR5bE32bBnFFcYtFuOS84nu9D+K6JJ5IvxKg+ZrY3ZZ1OxgEJiPIbIpFaan01F5j5YZFCIz3CIniz7PSliIKa4ULwZJwBo+7TnhODZWg5fiHSvrP7Ap6chG+6Ssm9/BsOM6BH2Oj75r4fERiagX9hl+AallNnebc5AHT8O5z/X7niTmzXWO0xmRtMOf2QKGPGfFLhu4ivvXbqM6/cBP9zMZbuOwh/KRWxFUi3JvvoywwztwahbDkOm2yG/80GTd2+z7EChB6dUPa1N1GK4IJWL88+bYw5l2MsgFWMYdoQquaNB2AenIcOgQDbvDZD9GL9H3h1yFJHNdtDjxKnrTSnOrn4JuTT8/Olhh6JVqz9eRAtFZXWA5fYGtL4FCcOhi7qg0u5lKyrCZI6f6cwqq7YwXoEASm3zhaIlsaAFRMBBp78G7C6ZqNZQqVLlyYxspAgAqnLObGf5epc9V4eqJJVehShUPaUueVT9sWiEIA/Xn3qvMBdHFMboRU7ZeEdI+sJ7ZEOoPv/Ha3MVYN9+lij0zwTF4uyfa5t5tCvdjjwjX3n0fwNs35SE7lAuvs8As7UwSVeSRnsSq3yFPBC1Qch8t08e0iUlLz70iJ+d4OIyaywD7aM=
