language: node_js
node_js:
- '6'
- '4'
- '0.12'
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
before_cache: npm prune
install: npm install
script: npm test
deploy:
- provider: npm
  email: ops@craft.ai
  api_key:
    secure: eNf/9wOC/uoHKKZGhUG1CGryKHBxuUIUkZhis/TVAGvh65D3LRfWU9kbGTbWmrFV7dQXgMRtZ0OZhevQ5c27gpVZKvIaNZynV53PpBtUwbtOE2vjbdie58PCNo7GKIJsAVfeiQta3pUUq6r9ZyN0573ROch+0pD2bNDLh+YT+JC54lnvGvceOZwajCsITecUgl7aev//6gnWr0cW3TDhNFyhAhpoy0r92g25i4M1IQ8D2nLZ46Wpi0ISL7xlT2DDp45w2ltu1bpJctNhymt1KTduTUbUHymVNceaHzq7llMA4DNhqtXD928JRa/TG2tnor9X7sGd4PUtheEsCJTX7OVrDMQnRnZTMRBXg3VBM/zLoNd6VLh38kddBQfh4cnlqYRyzcPdT5tbBYwmv34BdpdAXoApd0n5hPWkTSBFhFqGcP+h8sU2xv1U96o6X0atCzZdo/2RvUfbqEOdqWRHSOc/suhEyGordJbH3TGE7W0OaWsuUzjm0b+HNcpWKFp2vdhjAgwLxZQ1WvMyXmSOqeQ1GCMbYMjcTiP/U2tpq4+SnNVzeAzZaFJ1TiSS0x18F/hl9FukBOdv1jxXH1AulCxi54EcIZjnMVni7J4oIRz+iMk1qCIS/UbZsEmGIzBWlYGqwKeZTO5eF48M6LBR/+aimhREKvaoyek/dJjdGQE=
  on:
    tags: true
    repo: craft-ai/craft-ai-client-js
    node: '0.12'
  skip_cleanup: true
env:
  global:
  - secure: umQajLopZLJ56oPpS3nCPX0eSF5nf4UGZITE41YZ37mxC8O+Rj9b+rrAaRO/WrJcbJc8pvL5C3LIuLu+AZVhtJLuHV5wOG0BqMR/5lX9qlWQxYLKrTCwrxSHx5iu7xaZHOMfJB/Byi7wI9BW39dY3ynUrGrbjxMToUu+VwT8qrlgf8Yh2gOG2HJceAC9KP458BGfL4Xe8jSIOgDb6tc85Hn+bgonKcjIGqmUgZPOulosvUZ0aIoFIhEg3qc72uRSz5bkmpKdOtUsMXztPfGsazmtwWRJckOEIvD1KpuXEcnOLNXKWtco+BgyrDh8M7yK+rmueH1n8X6G7p+Xjo3S9ndjNIHd5kPxi3bq70hzUSFmq6PjCqLBOyts9C3rS2bO/cDj5oy76tUZGi0AxKXC3AgsarLXO55IKo7eeLZAfisa30NKsufuKk149+ympcyc1g6XZinY9eV/YtmllTLD00LwjKgxlRRLLo0SMeTo+SWDV34fMEnMUKTNtPyHxCKRWk6zTvc7fc5grPQVKo9f75hhD4wjHCxbQkhR6GAjcc3mtlL/Vskz1Ho1qvkqCYP05XbdKG00E6NRpRBlUzl1Bdzj3SXAqx5eJ4Vlg9V/IHL/HyhZKjwQEqQsjUczlhvOqzglBL6Ke+rz1xqY3HIuL6ILGfvgnJwrxhl1RY8BF0s=
  - secure: ZcVD5UmvfNv9O3B9yaNxoIabKNSiXg+51/2ysCbhONbdU6mAn9UwoPNLSVHN1Zx6DtiA9tl82b0iwsk4r3Fj2oEkZ5VENb6RgFs4X32xtRfc1fKTL8wfBC4HURl6KhUh/WwR7Jwn5gArIYvj5TmhHYNRQL7s/IsAe4ilKkauPotcYciajZg70JvpL+EktzzTXGEhJmSmgPvWf2XKAw9FDJHyG2Ie8rTet1SJcsqMpX+CyOtSN7jc+bHHI9+8gr7ItLFWnFmiy0YDtehnwehCgDlWoCIFFIuNResWtZCD6FaLRIDrVYxLFWchMIxWdkhUnMKylUag7h3iVqW5Y5kivM5hHR7kzDB1L6eabt/vyPn+9pZyZIazfPs5Q9umQVoZ3dLAESj/hhtqsupVG+HPbx4LGwG2H573UlWi+I5Y2uxCuBgYRQmqnI/BOOMoiOmc0A87a/I/nIoPIOhhrZeiGJ43AEA3N1rMU1YhC/TjaqPI9dwBEedqNjF3ojVUpfzD9faqvPO355Z6bTBXNJq2qle/9p2ufmA37hQVHJQuW1uBNZa3hPGPjQeGxDpHXn8LcOthHz59gPaBbShP0w/JuClyUWI4D4u66meXOW2Rbb0JPzIrBUhBk8RlMnbMcgBW6gZ2ToE1aFA2BSKDnTWcg7dslmZQEF7mBeHAiMSqMKE=
  - secure: fXfk1rqjBhYQaB/uQUjv/kofmFIHPIy83+96QwGyfWQUAIX9JZ9mTLT8s4ljDHlF9+FlYQssND0usuY9sdrIlfprG9dMa6qH7rcxYdTgq5ONlcHG90LFkARALBKnhPM7ADfFT61InAxfJeC3l/I50lakyVuhYdIu2dtB2suf+NPPvxSQclo92mmBtQ3QVhPBgwpppsj2p28SXWWd0fKZ8Dp1V69QPNcigshtazJss0cnUsytqmx2H//oHkZ0MC2Pn7cb4z9cU7FC1KMhtWdyF2EcFwruMXJ8zzyvjKQQG8Il1qtUYoa8oyZZCJEWOQlZq53hO1e0UZkEY0+zEayPbPjp6XS6lZq46Hw5+yy+up3pgU0vMYaF5iYQM74T7ZeD1YPfZsyQfKmyzO/d9Pm8PmEgLVJITuJ1gG09Ogtcu9J+hEx4KMmGo5g0O94CtUDd1DzqlFBaoIBeRKbgezBeRV/05mr4kWWFdc0FbgVKeGLO/RDP7v+D2XJutUjB1VOaEck9AGYvgLBT2eezgaVgBIPaPIlvZwOdTG9MvllwtA3ZfzU8xW2Ve7pph+OjhGKi2MCIzyouPC6+L991D8Q1yg4bECc+fha1XpMHu25RgqxNj/WKWxY5PsaTwZNZNmuW/6SMFodP4H07BYkhuobdumfZzKcIH5XDbpdbcMNK6RY=
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email:
  - ops@craft.ai
