name: test js client
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["10.x", "12.x"]
        include:
        # Define a build_id for each matrix config
          - node-version: "10.x"
            build_id: ${{ github.run_number }}0
            to_publish: false
          - node-version: "12.x"
            build_id: ${{ github.run_number }}1
            to_publish: true
    steps:
      # Preparing test/build environment 
      - name: Checkout scm
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: Run test
        env: 
          CRAFT_TOKEN: ${{ secrets.STANLEY_CRAFT_AI_TOKEN }}
          JOB_ID: ${{ matrix.build_id }}
        run: npm test
      - name: Build package
        if: ${{ matrix.to_publish  == true }}
        run: npm release
      - name: Save build artefact
        if: ${{ matrix.to_publish  == true }} && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/upload-artifact@master
        with:
          name: js-package
          path: dist/
            
  publish:
    # if tagged, build and publish
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: checkout scm
        uses: actions/checkout@master
      - name: Set up node 12.x
        uses: actions/setup-python@v2
        with:
          node-version: "12.x"
      - uses: actions/download-artifact@master
        with:
          name: js-package
          path: dist/